version: "1.0"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
        - SPRING_DATASOURCE_URL=jdbc:jdbc:derby:prodDB;create=true
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=admin137dark3



